### ISSUE TITLE
Koding.com Referral Train

### ISSUE THREAD

**Issue by RobertHerhold** [WHSCSC/WebApp#1]
## **Do not sign up for a Koding account until I call your name**

In order for this to work smoothly, it is *imperative* that only **one person** signs up per referral link.

You will need to sign up for an account on Koding, which is a cloud-based complete development environment, which will allow us to develop our software from anywhere without installing software on any computers. In order for us to get more disk space in our workspaces, we need to sign up with **referrals** from other people. For each referral, the **referrer** and the **person being referred** gets 0.5GB of extra disk space. Therefore, if everyone is both referred from somebody else and refers someone in return, everyone will get an extra gigabyte of storage.

As I call your name, you will click the referral link from the last person in the chain, and sign up using that link. **Sign up using your GitHub account**

![Signing up with GitHub](http://i.imgur.com/xCmHsv1.png)
 
Then, you will post a comment in this thread in the following format: `https://koding.com/R/<your username here>`. 

I will start the referral train below.

**Comment by RobertHerhold** [comment]
https://koding.com/R/robertherhold

**Comment by mightyjakethedog** [comment]
http://koding.com/R/mightyjakethedog

**Comment by kcdodaro** [comment]
http://koding.com/R/kcdodaro

**Comment by DavyJoes** [comment]
http://koding.com/R/DavyJoes

**Comment by epmancini** [comment]
http://koding.com/R/epmancini

**Comment by RyanFromSchool** [comment]
http://koding.com/R/RyanFromSchool

**Comment by josephd919** [comment]
http://koding.com/R/josephd919

**Comment by johnnie1998** [comment]
http://koding.com/R/johnnie1998

**Comment by jahniah223** [comment]
http://koding.com/R/jahniah223

**Comment by alecashforth** [comment]
https://koding.com/R/alecashforth
